# environment.yml - Minimal Conda environment for genie_test_cases in WSL
name: genie-test-wsl
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12       # Updated to Python 3.12
  - pysam=0.23.0        # Pinned to specific version
  - tqdm>=4.66.0      # Added with minimum version
  - colorama>=0.4.6   # Added for terminal formatting
  - pip               # Maintained for any pip-only needs
